<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gebruiker extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Gebruiker_model');
    } 

    /*
     * Listing of gebruiker
     */
    function index()
    {
        $data['gebruiker'] = $this->Gebruiker_model->get_all_gebruiker();
        
        $data['_view'] = 'gebruiker/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new gebruiker
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'gebruikertypeId' => $this->input->post('gebruikertypeId'),
				'klasId' => $this->input->post('klasId'),
				'trajectId' => $this->input->post('trajectId'),
				'afspraakId' => $this->input->post('afspraakId'),
				'voornaam' => $this->input->post('voornaam'),
				'achternaam' => $this->input->post('achternaam'),
				'email' => $this->input->post('email'),
				'passwoord' => $this->input->post('passwoord'),
            );
            
            $gebruiker_id = $this->Gebruiker_model->add_gebruiker($params);
            redirect('gebruiker/index');
        }
        else
        {            
            $data['_view'] = 'gebruiker/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a gebruiker
     */
    function edit($id)
    {   
        // check if the gebruiker exists before trying to edit it
        $data['gebruiker'] = $this->Gebruiker_model->get_gebruiker($id);
        
        if(isset($data['gebruiker']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'gebruikertypeId' => $this->input->post('gebruikertypeId'),
					'klasId' => $this->input->post('klasId'),
					'trajectId' => $this->input->post('trajectId'),
					'afspraakId' => $this->input->post('afspraakId'),
					'voornaam' => $this->input->post('voornaam'),
					'achternaam' => $this->input->post('achternaam'),
					'email' => $this->input->post('email'),
					'passwoord' => $this->input->post('passwoord'),
                );

                $this->Gebruiker_model->update_gebruiker($id,$params);            
                redirect('gebruiker/index');
            }
            else
            {
                $data['_view'] = 'gebruiker/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The gebruiker you are trying to edit does not exist.');
    } 

    /*
     * Deleting gebruiker
     */
    function remove($id)
    {
        $gebruiker = $this->Gebruiker_model->get_gebruiker($id);

        // check if the gebruiker exists before trying to delete it
        if(isset($gebruiker['id']))
        {
            $this->Gebruiker_model->delete_gebruiker($id);
            redirect('gebruiker/index');
        }
        else
            show_error('The gebruiker you are trying to delete does not exist.');
    }
    
}
