<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gebruiker_lesmoment extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Gebruiker_lesmoment_model');
    }
}
