<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gebruiker extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Gebruiker_model');
    } 

    /*
     * Listing of gebruiker
     */
    function index()
    {
        $data['gebruiker'] = $this->Gebruiker_model->get_all_gebruiker();
        
        $data['_view'] = 'gebruiker/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new gebruiker
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('email','Email','required');
		$this->form_validation->set_rules('passwoord','Passwoord','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'passwoord' => $this->input->post('passwoord'),
				'voornaam' => $this->input->post('voornaam'),
				'achternaam' => $this->input->post('achternaam'),
				'email' => $this->input->post('email'),
            );
            
            $gebruiker_id = $this->Gebruiker_model->add_gebruiker($params);
            redirect('gebruiker/index');
        }
        else
        {            
            $data['_view'] = 'gebruiker/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a gebruiker
     */
    function edit($idGebruiker)
    {   
        // check if the gebruiker exists before trying to edit it
        $data['gebruiker'] = $this->Gebruiker_model->get_gebruiker($idGebruiker);
        
        if(isset($data['gebruiker']['idGebruiker']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('email','Email','required');
			$this->form_validation->set_rules('passwoord','Passwoord','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'passwoord' => $this->input->post('passwoord'),
					'voornaam' => $this->input->post('voornaam'),
					'achternaam' => $this->input->post('achternaam'),
					'email' => $this->input->post('email'),
                );

                $this->Gebruiker_model->update_gebruiker($idGebruiker,$params);            
                redirect('gebruiker/index');
            }
            else
            {
                $data['_view'] = 'gebruiker/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The gebruiker you are trying to edit does not exist.');
    } 

    /*
     * Deleting gebruiker
     */
    function remove($idGebruiker)
    {
        $gebruiker = $this->Gebruiker_model->get_gebruiker($idGebruiker);

        // check if the gebruiker exists before trying to delete it
        if(isset($gebruiker['idGebruiker']))
        {
            $this->Gebruiker_model->delete_gebruiker($idGebruiker);
            redirect('gebruiker/index');
        }
        else
            show_error('The gebruiker you are trying to delete does not exist.');
    }
    
}
