<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kla extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kla_model');
    } 

    /*
     * Listing of klas
     */
    function index()
    {
        $data['klas'] = $this->Kla_model->get_all_klas();
        
        $data['_view'] = 'kla/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kla
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'naam' => $this->input->post('naam'),
				'maxAantal' => $this->input->post('maxAantal'),
            );
            
            $kla_id = $this->Kla_model->add_kla($params);
            redirect('kla/index');
        }
        else
        {            
            $data['_view'] = 'kla/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kla
     */
    function edit($id)
    {   
        // check if the kla exists before trying to edit it
        $data['kla'] = $this->Kla_model->get_kla($id);
        
        if(isset($data['kla']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'naam' => $this->input->post('naam'),
					'maxAantal' => $this->input->post('maxAantal'),
                );

                $this->Kla_model->update_kla($id,$params);            
                redirect('kla/index');
            }
            else
            {
                $data['_view'] = 'kla/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kla you are trying to edit does not exist.');
    } 

    /*
     * Deleting kla
     */
    function remove($id)
    {
        $kla = $this->Kla_model->get_kla($id);

        // check if the kla exists before trying to delete it
        if(isset($kla['id']))
        {
            $this->Kla_model->delete_kla($id);
            redirect('kla/index');
        }
        else
            show_error('The kla you are trying to delete does not exist.');
    }
    
}
