<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Afspraak_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get afspraak by id
     */
    function get_afspraak($id)
    {
        return $this->db->get_where('afspraak',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all afspraak
     */
    function get_all_afspraak()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('afspraak')->result_array();
    }
        
    /*
     * function to add new afspraak
     */
    function add_afspraak($params)
    {
        $this->db->insert('afspraak',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update afspraak
     */
    function update_afspraak($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('afspraak',$params);
    }
    
    /*
     * function to delete afspraak
     */
    function delete_afspraak($id)
    {
        return $this->db->delete('afspraak',array('id'=>$id));
    }
}
