<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gebruiker_lesmoment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gebruiker_lesmoment by 
     */
    function get_gebruiker_lesmoment($)
    {
        return $this->db->get_where('gebruiker_lesmoment',array(''=>$))->row_array();
    }
        
    /*
     * Get all gebruiker_lesmoment
     */
    function get_all_gebruiker_lesmoment()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('gebruiker_lesmoment')->result_array();
    }
        
    /*
     * function to add new gebruiker_lesmoment
     */
    function add_gebruiker_lesmoment($params)
    {
        $this->db->insert('gebruiker_lesmoment',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gebruiker_lesmoment
     */
    function update_gebruiker_lesmoment($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('gebruiker_lesmoment',$params);
    }
    
    /*
     * function to delete gebruiker_lesmoment
     */
    function delete_gebruiker_lesmoment($)
    {
        return $this->db->delete('gebruiker_lesmoment',array(''=>$));
    }
}
