<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gebruikertype_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gebruikertype by id
     */
    function get_gebruikertype($id)
    {
        return $this->db->get_where('gebruikertype',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all gebruikertype
     */
    function get_all_gebruikertype()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('gebruikertype')->result_array();
    }
        
    /*
     * function to add new gebruikertype
     */
    function add_gebruikertype($params)
    {
        $this->db->insert('gebruikertype',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gebruikertype
     */
    function update_gebruikertype($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('gebruikertype',$params);
    }
    
    /*
     * function to delete gebruikertype
     */
    function delete_gebruikertype($id)
    {
        return $this->db->delete('gebruikertype',array('id'=>$id));
    }
}
