<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gebruiker_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gebruiker by id
     */
    function get_gebruiker($id)
    {
        return $this->db->get_where('gebruiker',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all gebruiker
     */
    function get_all_gebruiker()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('gebruiker')->result_array();
    }
        
    /*
     * function to add new gebruiker
     */
    function add_gebruiker($params)
    {
        $this->db->insert('gebruiker',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gebruiker
     */
    function update_gebruiker($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('gebruiker',$params);
    }
    
    /*
     * function to delete gebruiker
     */
    function delete_gebruiker($id)
    {
        return $this->db->delete('gebruiker',array('id'=>$id));
    }
}
