<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lokaal_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lokaal by id
     */
    function get_lokaal($id)
    {
        return $this->db->get_where('lokaal',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all lokaal
     */
    function get_all_lokaal()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('lokaal')->result_array();
    }
        
    /*
     * function to add new lokaal
     */
    function add_lokaal($params)
    {
        $this->db->insert('lokaal',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lokaal
     */
    function update_lokaal($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('lokaal',$params);
    }
    
    /*
     * function to delete lokaal
     */
    function delete_lokaal($id)
    {
        return $this->db->delete('lokaal',array('id'=>$id));
    }

}
