<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vak_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get vak by id
     */
    function get_vak($id)
    {
        return $this->db->get_where('vak',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all vak
     */
    function get_all_vak()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('vak')->result_array();
    }
        
    /*
     * function to add new vak
     */
    function add_vak($params)
    {
        $this->db->insert('vak',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update vak
     */
    function update_vak($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('vak',$params);
    }
    
    /*
     * function to delete vak
     */
    function delete_vak($id)
    {
        return $this->db->delete('vak',array('id'=>$id));
    }
    //uurrooster in vak
    function insertVak($dataVak)
    {
        $this->db->insert('vak', $dataVak);
        return $this->db->insert_id();

    }
}
