<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gebruiker_has_lesmoment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gebruiker_has_lesmoment by Gebruiker_idGebruiker
     */
    function get_gebruiker_has_lesmoment($Gebruiker_idGebruiker)
    {
        return $this->db->get_where('Gebruiker_has_Lesmoment',array('Gebruiker_idGebruiker'=>$Gebruiker_idGebruiker))->row_array();
    }
        
    /*
     * Get all gebruiker_has_lesmoment
     */
    function get_all_gebruiker_has_lesmoment()
    {
        $this->db->order_by('Gebruiker_idGebruiker', 'desc');
        return $this->db->get('Gebruiker_has_Lesmoment')->result_array();
    }
        
    /*
     * function to add new gebruiker_has_lesmoment
     */
    function add_gebruiker_has_lesmoment($params)
    {
        $this->db->insert('Gebruiker_has_Lesmoment',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gebruiker_has_lesmoment
     */
    function update_gebruiker_has_lesmoment($Gebruiker_idGebruiker,$params)
    {
        $this->db->where('Gebruiker_idGebruiker',$Gebruiker_idGebruiker);
        return $this->db->update('Gebruiker_has_Lesmoment',$params);
    }
    
    /*
     * function to delete gebruiker_has_lesmoment
     */
    function delete_gebruiker_has_lesmoment($Gebruiker_idGebruiker)
    {
        return $this->db->delete('Gebruiker_has_Lesmoment',array('Gebruiker_idGebruiker'=>$Gebruiker_idGebruiker));
    }
}
