<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gebruiker_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gebruiker by idGebruiker
     */
    function get_gebruiker($idGebruiker)
    {
        return $this->db->get_where('Gebruiker',array('idGebruiker'=>$idGebruiker))->row_array();
    }
        
    /*
     * Get all gebruiker
     */
    function get_all_gebruiker()
    {
        $this->db->order_by('idGebruiker', 'desc');
        return $this->db->get('Gebruiker')->result_array();
    }
        
    /*
     * function to add new gebruiker
     */
    function add_gebruiker($params)
    {
        $this->db->insert('Gebruiker',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gebruiker
     */
    function update_gebruiker($idGebruiker,$params)
    {
        $this->db->where('idGebruiker',$idGebruiker);
        return $this->db->update('Gebruiker',$params);
    }
    
    /*
     * function to delete gebruiker
     */
    function delete_gebruiker($idGebruiker)
    {
        return $this->db->delete('Gebruiker',array('idGebruiker'=>$idGebruiker));
    }
}
