<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kla_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kla by id
     */
    function get_kla($id)
    {
        return $this->db->get_where('Klas',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all klas
     */
    function get_all_klas()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('Klas')->result_array();
    }
        
    /*
     * function to add new kla
     */
    function add_kla($params)
    {
        $this->db->insert('Klas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kla
     */
    function update_kla($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('Klas',$params);
    }
    
    /*
     * function to delete kla
     */
    function delete_kla($id)
    {
        return $this->db->delete('Klas',array('id'=>$id));
    }
}
