<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lesmoment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lesmoment by id
     */
    function get_lesmoment($id)
    {
        return $this->db->get_where('Lesmoment',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all lesmoment
     */
    function get_all_lesmoment()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('Lesmoment')->result_array();
    }
        
    /*
     * function to add new lesmoment
     */
    function add_lesmoment($params)
    {
        $this->db->insert('Lesmoment',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lesmoment
     */
    function update_lesmoment($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('Lesmoment',$params);
    }
    
    /*
     * function to delete lesmoment
     */
    function delete_lesmoment($id)
    {
        return $this->db->delete('Lesmoment',array('id'=>$id));
    }
}
