<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Traject_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get traject by id
     */
    function get_traject($id)
    {
        return $this->db->get_where('Traject',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all traject
     */
    function get_all_traject()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('Traject')->result_array();
    }
        
    /*
     * function to add new traject
     */
    function add_traject($params)
    {
        $this->db->insert('Traject',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update traject
     */
    function update_traject($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('Traject',$params);
    }
    
    /*
     * function to delete traject
     */
    function delete_traject($id)
    {
        return $this->db->delete('Traject',array('id'=>$id));
    }
}
